### ISSUE TITLE
Relax dependency boundaries on yesod-core and yesod-form

### ISSUE THREAD

**Issue by nek0** [pbrisbin/yesod-markdown#20]
Hello there,

I am currently using your library in my project [eidolon](https://github.com/nek0/eidolon), but when building it normally, I run into dependency hell. I averted it by removing the upper boundaries of the dependencies for `yesod-core` and `yesod-form`. Can you please consider relaxing your upper boundaries?

**Comment by nek0** [comment]
Hi there,

i created a pull request, as you suggested.

**Comment by pbrisbin** [comment]
Awesome thanks. Closing this to consolidate any discussion over in the PR.
