### ISSUE TITLE
convert markdown  data (from DB) to html 

### ISSUE THREAD

**Issue by MonrealRyan** [pbrisbin/yesod-markdown#24]
Hi, 
I'll already save my markdown data on my DB (PostGreSQL).
now once i retrieve it, i want my markdown to converted first to HTML before to render in my hamlet.

hope you help me, thank you.

**Comment by pbrisbin** [comment]
Make your database field type `Markdown`.

**config/models**

```
Person
    bio Markdown
```

**Handler.PersonR**

```
getPersonR :: PersonId -> Handler Html
getPersonR pid = do
    person <- runDB $ get404 pid
    defaultLayout $ [whamlet| #{personBio person} |]
```

**Comment by MonrealRyan** [comment]
@pbrisbin - i'll already do that. but my IDE i think doesnt support that. i'll also created a top on [Yesod Google Groups](https://groups.google.com/forum/#!topic/yesodweb/Eux2ZH7c7mM) for that..

**Comment by pbrisbin** [comment]
I'm not sure what the IDE has to do with anything, but good luck resolving your issue on the ML.
