### ISSUE TITLE
Relax blaze-html upper bound

### ISSUE THREAD

**Issue by geraldus** [pbrisbin/yesod-markdown#25]
I have this package as build dependency in my project. Yesterday I switched to GHC 7.8.4 and cabal-1.22, Stackage LTS 2.1. Now, when I try to install `yesod-markdown` cabal tries install version 0.2.1, because of `blaze-html < 0.8` constraint: LTS 2.1 Stackage snapshot have `blaze-html ==0.8.0.2` constraint, thus cabal could pick version `0.2.1`, since it is highest version which have no `blaze-html` dependency at all. All next versions are rejected. But this version is too old, and unsurprisingly fails to install:

```
Preprocessing library yesod-markdown-0.2.1...

Yesod/Markdown.hs:21:8:
    Could not find module ‘Yesod.Form.Core’
    Perhaps you meant
      Yesod.Form.Types (needs flag -package yesod-form-1.4.4.1)
      Yesod.Form.Nic (needs flag -package yesod-form-1.4.4.1)
    Use -v to see a list of the files searched for.
``` 

Relaxing upper bound of `blaze-html` to `< 0.9` makes package buildable, however I still can't install it, the error message is quite confusing to me:

```
> cabal install
Resolving dependencies...
Configuring yesod-markdown-0.9.3.1...
Building yesod-markdown-0.9.3.1...
Failed to install yesod-markdown-0.9.3.1
Build log ( /Users/arthurfayzrakhmanov/.cabal/logs/yesod-markdown-0.9.3.1.log ):
Configuring yesod-markdown-0.9.3.1...
Building yesod-markdown-0.9.3.1...
setup-Simple-Cabal-1.18.1.5-x86_64-osx-ghc-7.8.4: dist/package.conf.inplace:
inappropriate type
cabal: Error: some packages failed to install:
yesod-markdown-0.9.3.1 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by nomeata** [comment]
While you are at it, please consider adding your package to stackage, so that you are notified of such problems before they affect the users.See http://www.stackage.org/authors for instructions.

**Comment by geraldus** [comment]
@nomeata oh, I've already forgot about this issue. I believe install problem was due to that fact I've forgot to update `Cabal` lib. I can recheck this stuff later on, but can't be certain about timing. Also, I've already moved to `markdown` package. I'm not neither an author nor maintainer of this package. Also this version is a folk of another one actually. Likely this package is not maintained by anyone at this moment.

**Comment by pbrisbin** [comment]
Hello! Sorry I didn't see this issue when it was opened, I try to be quicker about it.

Yes, `markdown` is a nice package. This package is useful if you specifically need pandoc features. I will probably not add it to stackage myself, but I welcome anyone else who wants to. I should be able to relax the bound and release a new version this week, but it would happen much faster if someone opened it as a PR.

**Comment by geraldus** [comment]
Closing in favour of https://github.com/pbrisbin/yesod-markdown/pull/27
