### ISSUE TITLE
Support base-4.8

### ISSUE THREAD

**Issue by pharpend** [pbrisbin/yesod-markdown#26]

**Comment by pbrisbin** [comment]
Thanks for the ping. I will attempt to compile on 7.10 this week.

**Comment by pbrisbin** [comment]
I just compiled yesod-markdown-0.9.4 successfully on 7.10. If you have trouble, please open a new issue with actual error messages.

**Comment by pharpend** [comment]
Oops! I opened this issue accidentally. I meant to open it on another library. Sorry!
