### ISSUE TITLE
Please consider joining stackage

### ISSUE THREAD

**Issue by nomeata** [pbrisbin/yesod-markdown#29]
Hi,

it would be easier for users and distro packages one can rely on what versions on hackage work together. Stackage solves this problem, and gives you free QA. Please consider joining stackage: http://www.stackage.org/authors

Greetings,
Joachim

**Comment by nomeata** [comment]
Hi. Any news on this?

**Comment by pbrisbin** [comment]
Sorry I missed this, for various unimportant reasons I don't get emailed for new issues and so I sometimes miss them.

Thanks for the suggestion, that has come up before. I welcome anyone willing to put my packages on stackage (would you like to?). I don't use stackage (not against it, just don't use it myself) and so I won't be putting my own packages up there.

**Comment by nomeata** [comment]
I’m busy enough managing the 700 packages for Debian.

Note that you do not have to use stackage to add your packages there. You simply tell them that your package should be part of it, and they start telling you when they break due to newer releases. It does not require you to use any tool or do anything different than otherwise. You can see it as an opt-in free quality assurance tool.

**Comment by iustin** [comment]
Hello,

I see that the project now has a stack.yaml file, so I would guess you started using stackage. Would you reconsider adding yesod-markdown to it (stackage) then?

**Comment by pbrisbin** [comment]
Holy old issue. `yesod-markdown` is in Stackage. I was generally willing to do it a long time ago, but only got around to it recently. See https://github.com/fpco/stackage/pull/3317.

**Comment by iustin** [comment]
Hah, sorry for that - the hackage page, where I usually check in which distributions a given package is, doesn't show stackage for yesod-markdown. All good, thanks!
