### ISSUE TITLE
version 0.9.4 missing haddocks

### ISSUE THREAD

**Issue by andrewthad** [pbrisbin/yesod-markdown#32]
haddocks have been missing for a while

**Comment by pbrisbin** [comment]
Thanks for reporting this. I'm about to release 0.10.0 and I'll see if the build then, and investigate if not.

**Comment by andrewthad** [comment]
Looks like it's missing in 0.10.0 as well.

**Comment by pbrisbin** [comment]
Maybe this?

```
haddock: /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-7.8.3/hslua-0.4.0/libHShslua-0.4.0.a: unknown symbol `deRefStablePtr'
Haddock coverage:
haddock: unable to load package `hslua-0.4.0'
```

**Comment by andrewthad** [comment]
Bump.

**Comment by pbrisbin** [comment]
Sorry, I really don't have an answer here or an idea of when I'll have time to dig into it.

**Comment by pbrisbin** [comment]
This appears to have corrected itself.

http://hackage.haskell.org/package/yesod-markdown-0.9.4/docs/Yesod-Markdown.html
