### ISSUE TITLE
update to work with pandoc 1.16

### ISSUE THREAD

**Issue by wolftune** [pbrisbin/yesod-markdown#33]
So, with Stackage LTS-5 and the pandoc update otherwise, it would be nice for yesod-markdown to support/allow pandoc 1.16. This is a breaking issue for those of us wanting to move to LTS-5 otherwise.

Incidentally, it would also be nice to get yesod-markdown into Stackage.

**Comment by pbrisbin** [comment]
Should be good in 0.11.0.
