### ISSUE TITLE
Release version that supports GHC 8.4

### ISSUE THREAD

**Issue by andrewthad** [pbrisbin/yesod-markdown#59]
A missing `Semigroup` instance makes the version on hackage not build with GHC 8.4+. A new release would be nice. It may also be worthwhile to retroactively add an upper bound on `base` to the most recent hackage releases.

**Comment by pbrisbin** [comment]
Huh. I would've expected the nightly CI build to have caught something like this. I'll look into it this week. FWIW, if you want to resolve this in a PR, it's probably more likely to happen faster that way.

**Comment by andrewthad** [comment]
It's already fixed in master. It just hasn't been released to hackage yet.

**Comment by pbrisbin** [comment]
Ohhhh. My bad.

**Comment by pbrisbin** [comment]
v0.12.4 released. I'll give the retroactive upper bounds some thought.
