### ISSUE TITLE
upload haddocks to hackage manually

### ISSUE THREAD

**Issue by cdepillabout** [pbrisbin/yesod-markdown#63]
It looks like the latest version of yesod-markdown ([0.12.6.0](http://hackage.haskell.org/package/yesod-markdown-0.12.6.0)) is missing haddocks on hackage.

It would be super helpful if you could upload these manually

**Comment by pbrisbin** [comment]
I couldn't get this to work on my initial attempts. If you have some docs or a script/tool that you like for doing this that might "Just Work" (and works on a Stack-based project), please let me know and I will try it. Otherwise, I think I'm just going to wait it out.

**Comment by cdepillabout** [comment]
Yeah, it's a pain to do with `stack`.

If you have `cabal` installed, you might be able to use this script I've been using.  (The instructions at the top say to use `nix-shell`, but all it should depend on is `cabal` being available.)

https://github.com/cdepillabout/termonad/blob/fc899181037742b61e66978e74f40ae04b35fdb8/scripts/hackage-docs.sh

I've fought a bunch with this script in the past, so if it doesn't work on the first try or so, I wouldn't put too much time into figuring it out.
