### ISSUE TITLE
Allow persistent 2.11

### ISSUE THREAD

**Issue by lf-** [pbrisbin/yesod-markdown#73]
I need persistent 2.11 to get a bugfix for a persistent-template regression. At present yesod-markdown has `persistent >= 0.9 && <2.11`.

**Comment by pbrisbin** [comment]
Bah, I think I unintentionally tightened this by an accidental `--pvp-bounds` on an upload. Will fix by Monday at the latest.

**Comment by pbrisbin** [comment]
Fixed in v0.12.6.5 -- sorry about that.
